img=c.imread("images/home.jpg",0)
print("shape->dimensions: ",img.shape)
print("size->numbers of pixels: ",img.size)
print("Type: ",img.dtype)
c.imshow("image", img)
img2=c.imread("images/home.jpg")
print('image2')
print("shape->dimensions: ",img2.shape)
print("size->numbers of pixels: ",img2.size)
print("Type: ",img2.dtype)
c.imshow("image2", img2)
c.waitKey(0)
c.destrovAllw
c.destroyAllWindows
c.dimg=c.imread("images/home.jpg",0)
print("shape->dimensions: ",img.shape)
print("size->numbers of pixels: ",img.size)
print("Type: ",img.dtype)
c.imshow("image", img)
img2=c.imread("images/home.jpg")
print('image2')
print("shape->dimensions: ",img2.shape)
print("size->numbers of pixels: ",img2.size)
print("Type: ",img2.dtype)
c.imshow("image2", img2)
c.waitKey(0)
c.destroyAllWindows ()
